swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /get:
    # I haven't changed this from the original world example the program auto creates
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /put:
    x-swagger-router-controller: hello_world
    put:
      description: Updates, not really, something. Tells you
      operationId: update
      parameters:
        - name: name
          description: name of the thing
          in: body
          required: true
          schema:
            $ref: "#/definitions/thing"
      responses:
        "200":
          description: Updated
          schema:
            $ref: "#/definitions/UpdateResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /post:
    x-swagger-router-controller: hello_world
    post:
      description: pretends to post something but not really becasue there is no database
      operationId: putIn
      parameters:
        - name: name
          description: name of the thing
          in: body
          required: true
          schema:
            $ref: "#/definitions/thing"
      responses:
        "201":
          description: Created
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /delete:
    x-swagger-router-controller: hello_world
    delete:
      description: makes an invisible item become really invisible
      operationId: goAway
      responses:
        "200":
          description: deleted
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  UpdateResponse:
    required:
      - message
    properties:
      message:
        type: string
  thing:
    type: object
    properties:
      name:
        type: string
        description: name of the the thing
    required:
      - name